### ISSUE TITLE
Forward-Peeking

### ISSUE THREAD

**Issue by dsstex** [alxgrin/kaggle#1]
Hi, 

I was going through your notebook: mczielinski_bitcoin-historical-data.ipynb

It looks like you are doing prediction incorrectly.

This is how your code looks like. 

```
# для бинарного обучения классификатора (up/down)
def accuracy_target(labels):
    labels_acc = labels.copy()
    labels_acc["Weighted_Price_1"] = labels.shift(1)["Weighted_Price"].fillna(0)
    labels_acc["Target"] = (
        labels_acc["Weighted_Price"] > labels_acc["Weighted_Price_1"]
    ).astype(int)
    return labels_acc


y = accuracy_target(y)
y = y[["Target"]]
y
```

You are comparing current_price with the last_price.  Since you are doing prediction and its all about the future price, you should compare current_price with the future_price. 

Let me explain. 

Your X contains  Open, High, Low, Close

Your y checks whether the current_price is gonna up or down from the last_price. 

When you do prediction you don't have access to current Open, High, Low, Close. You only have access to the finished candle. i.e. last_candle. So You need to use that last_candle to predict the price of current uncompleted candle. 

So your target code should look like this.  

```
# для бинарного обучения классификатора (up/down)
def accuracy_target(labels):
    labels_acc = labels.copy()
    labels_acc["Weighted_Price_1"] = labels.shift(-1)["Weighted_Price"].fillna(0)
    labels_acc["Target"] = (
        labels_acc["Weighted_Price"] < labels_acc["Weighted_Price_1"]
    ).astype(int)
    return labels_acc


y = accuracy_target(y)
y = y[["Target"]]
y
```

In that code, I changed two lines. 

`labels.shift(1)` becomes `labels.shift(-1)`  

and 

` labels_acc["Weighted_Price"] > labels_acc["Weighted_Price_1"]` becomes `labels_acc["Weighted_Price"] < labels_acc["Weighted_Price_1"]`

Hope that helps.

**Comment by alxgrin** [comment]
Thanks for your comment, fixed
